### ISSUE TITLE
哔咔登录链接超时

### ISSUE THREAD

**Issue by juicemock** [wgh136/PicaComic#238]
### Content

正常登录链接超时 开梯子显示错误代码请问 这是什么问题呢？

**Comment by wgh136** [comment]
错误代码是什么

________________________________
From: juicemock ***@***.***>
Sent: Sunday, October 29, 2023 12:03:36 PM
To: wgh136/PicaComic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wgh136/PicaComic] 哔咔登录链接超时 (Issue #238)


Content

正常登录链接超时 开梯子显示错误代码请问 这是什么问题呢？

―

**Comment by juicemock** [comment]
使用转发服务器会出现Error : SocketException : Connection reset by peer ( OS Error : Connection reset by peer , errno =104), address = api . kokoiro . xyz , port =35052  不使用转发服务器就连接超时
旧版1.6.17的开梯子就可以直接登录 新版好像不行

**Comment by wgh136** [comment]
挂梯子也不能登录？
Connection reset by peer通常是因为被墙了
________________________________

**Comment by juicemock** [comment]
但旧版依旧无法使用哔咔 页面显示连接超时

**Comment by wgh136** [comment]
这我没办法解决，如果挂梯子也不行建议看看你梯子的日志

________________________________

**Comment by juicemock** [comment]
禁漫可以使用 哔咔是连接超时

**Comment by juicemock** [comment]
好的

**Comment by juicemock** [comment]
哔咔一般是怎么才能登上呢？

**Comment by juicemock** [comment]
新版挂梯子是这个代码 type ' String ' is not a subtype of type ' int ' of 
' index '

**Comment by wgh136** [comment]
使用没问题的梯子就不存在问题，哔咔的服务器很稳定，接口也一直没变，如果你的梯子能正常访问其他被墙的东西，那么可能是分流规则的问题，试试开全局模式
我的转发服务器可能是在部分地区被墙了

________________________________

**Comment by juicemock** [comment]
明白了

**Comment by wgh136** [comment]
提供下完整的错误信息，在设置-logs里面可以看

________________________________

**Comment by wgh136** [comment]
邮件有延迟

> 新版挂梯子是这个代码 type ' String ' is not a subtype of type ' int ' of
' index '

这个应该是app的问题，发一下app的日志

**Comment by juicemock** [comment]
我用邮件发您了 您看看有没有收到

**Comment by wgh136** [comment]
没有，你可以直接在这里上传

**Comment by juicemock** [comment]
Logs

info Network 2023-10-29 13:25:04.541115 
Set Proxy null

info Network 2023-10-29 13:25:04.541348 
Set Proxy null

error Unhandled Exception 2023-10-29 13:25:04.541583 
PlatformException(error, Missing type parameter., null, java.lang.RuntimeException: Missing type parameter.
	at j1.a.d(SourceFile:1)
	at j1.a.<init>(SourceFile:1)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin$a.<init>(Unknown Source:0)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.loadScheduledNotifications(Unknown Source:25)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.removeNotificationFromCache(Unknown Source:0)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.cancelNotification(Unknown Source:53)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.cancel(SourceFile:1)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(SourceFile:1)
	at e2.k$a.a(SourceFile:1)
	at u1.c.l(SourceFile:1)
	at u1.c.m(SourceFile:1)
	at u1.c.i(SourceFile:1)
	at u1.b.run(SourceFile:1)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8673)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310)
<asynchronous suspension>
#2      FlutterLocalNotificationsPlugin.cancel (package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart:280)
<asynchronous suspension>
#3      Notifications.endProgress (package:pica_comic/tools/notification.dart:94)
<asynchronous suspension>


info Network 2023-10-29 13:25:04.542602 
GET https://api.kokoiro.xyz/version
headers:
{}
data:null

info Network 2023-10-29 13:25:04.543139 
POST https://www.jmapinode1.top/login
headers:
{token: ccf1c2fda99741aaf206a8c7f29722f2, tokenparam: 1698557104,1.6.1, user-agent: Mozilla/5.0 (Linux; Android 13; 8d41w854d Build/TQ1A.230205.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.196 Safari/537.36, accept-encoding: gzip, Host: www.jmapinode1.top, Content-Type: application/x-www-form-urlencoded}
data:username=rejic666&password=rjc700898

error Network 2023-10-29 13:25:04.881727 
GET https://api.kokoiro.xyz/version
DioException [unknown]: null
Error: SocketException: Connection reset by peer (OS Error: Connection reset by peer, errno = 104), address = api.kokoiro.xyz, port = 57706

info Network 2023-10-29 13:25:06.366515 
Response https://www.jmapinode1.top/login
headers:
connection: keep-alive
cache-control: no-store, no-cache, must-revalidate
set-cookie: ipcountry=CN; path=/
set-cookie: ipm5=d01817e5f51de0bb255bc92d1fe8137f; path=/
set-cookie: AVS=ckt467ve46ga0ajic73ccrr2i7; path=/
set-cookie: remember_id=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/
last-modified: Sun, 29 Oct 2023 05:25:05 GMT
date: Sun, 29 Oct 2023 05:25:06 GMT
vary: Accept-Encoding
content-encoding: gzip
cf-cache-status: DYNAMIC
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=0UJC58P05O2olrlBeVsXooIBSlgWOgXqPMDhOoUhuQoquRUUksBt6aRcP0GBg97SqJksGLcdvm7UGZkBHF1xaCfximu6gTKR2yhMKdIRmWEIKH4Sg0kl%2FYUuPhW4Z%2Ff0j9FYMH5R1ghPl3%2F8U07NQA8%3D"}],"group":"cf-nel","max_age":604800}
pragma: no-cache
content-type: application/javascript; charset=utf-8;
server: cloudflare
alt-svc: h3=":443"; ma=86400
content-length: 467
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
cf-ray: 81d8fef7aaee17d1-SJC
expires: Thu, 19 Nov 1981 08:52:00 GMT

[10, 123, 34, 99, 111, 100, 101, 34, 58, 50, 48, 48, 44, 34, 100, 97, 116, 97, 34, 58, 34, 70, 101, 50, 49, 65, 119, 81, 100, 106, 82, 107, 90, 69, 107, 118, 69, 102, 80, 70, 43, 71, 114, 51, 121, 43, 51, 67, 111, 110, 73, 113, 92, 47, 119, 76, 113, 48, 84, 107, 90, 114, 121, 50, 69, 87, 66, 111, 98, 105, 121, 122, 85, 102, 119, 77, 114, 108, 87, 101, 67, 97, 49, 89, 113, 65, 54, 52, 89, 66, 118, 114, 55, 73, 118, 80, 112, 81, 72, 49, 56, 67, 107, 73, 82, 82, 82, 118, 110, 69, 110, 85, 113, 110, 122, 54, 65, 48, 98, 119, 55, 53, 89, 109, 114, 57, 50, 114, 103, 57, 56, 48, 82, 90, 88, 85, 43, 86, 75, 70, 54, 118, 99, 116, 118, 68, 73, 104, 107, 106, 82, 74, 81, 97, 105, 89, 119, 66, 118, 57, 55, 75, 104, 100, 121, 102, 114, 75, 112, 50, 68, 121, 107, 48, 82, 54, 97, 56, 84, 55, 49, 88, 86, 115, 112, 97, 101, 51, 52, 50, 51, 86, 72, 110, 100, 119, 79, 90, 108, 110, 80, 67, 108, 76, 65, 107, 72, 111, 98, 112, 80, 108, 111, 78, 73, 121, 116, 99, 87, 49, 116, 53, 97, 111, 50, 99, 57, 83, 49, 79, 111, 77, 113, 68, 53, 68, 120, 79, 68, 4

**Comment by juicemock** [comment]
我这手机上用github 附件显示不出来

**Comment by wgh136** [comment]
点那个图片的图标然后选择要发送的文件，然后等待上传完成，再发送

**Comment by wgh136** [comment]
不行的话还是发我邮箱
nyne19710@proton.me

**Comment by wgh136** [comment]
收到了，等我看看是什么情况

**Comment by wgh136** [comment]
```
error Network 2023-10-29 13:33:23.225115 
Response https://picaapi.picacomic.com/auth/sign-in
headers:
connection: keep-alive
date: Sun, 29 Oct 2023 05:33:23 GMT
content-length: 79
cf-cache-status: DYNAMIC
cf-ray: 81d90b1f0ca68eff-HKG
content-type: application/json; charset=utf-8
server: cloudflare

{"code":400,"error":"1004","message":"invalid email or password","detail":":("}

error Network 2023-10-29 13:33:23.225884 
type 'String' is not a subtype of type 'int' of 'index'
#0      PicacgNetwork.post (package:pica_comic/network/picacg_network/methods.dart:113)
<asynchronous suspension>
#1      PicacgNetwork.login (package:pica_comic/network/picacg_network/methods.dart:145)
<asynchronous suspension>
```
账号或密码错误
你用正确的账号及密码再试试
app没能捕获这一错误，下个版本会进行修复

**Comment by juicemock** [comment]
是挂梯子登录吗

**Comment by wgh136** [comment]
是的

________________________________

**Comment by juicemock** [comment]
登进去了非常感谢 我记得以前不挂梯子就能看 是开了转发服务器吗 现在只有挂梯子才能用了 是因为转发服务器不能用了吗

**Comment by wgh136** [comment]
看了一下日志，转发服务器的域名被解析到了一个高位端口，这应该是部分地区的运营商把我的转发服务器给墙了，我的域名快到期了，下个版本更新时会换一个，看看能不能解决问题
想稳定使用还是需要梯子

**Comment by juicemock** [comment]
好的好的 十分感谢
