### ISSUE TITLE
[Bug]: 下载目标服务器不存在的文件时会卡死，无法继续下载

### ISSUE THREAD

**Issue by HanHan518** [wgh136/PicaComic#392]
### 描述/Description

例如 来自哔咔"G1 P站杂图"第八话第37张，当下载此文件时，访问下载地址会返回会"Invalid source image"，同时下载管理器会在一段时间后提示下载错误，导致该下载任务无法完成

### Version

latest

### 使用的操作系统/Operating system

Android, Windows

### 日志/logs

部分相关日志
Network error
GET https://storage-b.picacomic.com/static/tobeimg/BSNFJIi6EL4ncbvT60W7jpL73wQX8zR3pZkNx45XKCw/rs:fit:800:800:0/g:ce/aHR0cHM6Ly9zdG9yYWdlLWIucGljYWNvbWljLmNvbS9zdGF0aWMvMjM1NjlmN2YtNjBhNC00N2I0LTk3ZmItODAxMGE1Y2JiYjRjLmpwZw.jpg
DioException [bad response]: The request returned an invalid status code of 422.

Unhandled Exception error
DioException [bad response]: The request returned an invalid status code of 422.
#0      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:507)
#1      _rootRunUnary (dart:async/zone.dart:1407)
#2      _CustomZone.runUnary (dart:async/zone.dart:1308)
#3      _FutureListener.handleError (dart:async/future_impl.dart:180)
#4      Future._propagateToListeners.handleError (dart:async/future_impl.dart:858)
#5      Future._propagateToListeners (dart:async/future_impl.dart:879)
#6      Future._completeError (dart:async/future_impl.dart:655)
#7      _SyncCompleter._completeError (dart:async/future_impl.dart:63)
#8      _Completer.completeError (dart:async/future_impl.dart:27)
#9      Future.any.onError (dart:async/future.dart:618)
#10     _rootRunBinary (dart:async/zone.dart:1423)
#11     _CustomZone.runBinary (dart:async/zone.dart:1315)
#12     _FutureListener.handleError (dart:async/future_impl.dart:177)
#13     Future._propagateToListeners.handleError (dart:async/future_impl.dart:858)
#14     Future._propagateToListeners (dart:async/future_impl.dart:879)
#15     Future._completeError (dart:async/future_impl.dart:655)
#16     Future._chainForeignFuture.<anonymous closure> (dart:async/future_impl.dart:556)
#17     _rootRun (dart:async/zone.dart:1399)
#18     _CustomZone.run (dart:async/zone.dart:1301)
#19     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

**Comment by HanHan518** [comment]
个人摸索出的解决方法
Android(需要Root)
退出Picacomic，使用MT管理器或其他能够访问根目录的文件管理，打开/data/user/0/com.github.wgh136.pica_comic/files/download文件夹，编辑newDownload.json文件，找到_downloadedNum和index字样，将冒号后的数字加1，如果为漫画最后一张，方式不变，如果为本话最后一张，则将_downloadingEp冒号后数字加1，并将index字样数字改为0，重新打开，继续下载即可
Windows
退出Picacomic，打开%appdata%\com.kokoiro.xyz\pica_comic\download文件夹，编辑newDownload.json，其他与Android一致
