### ISSUE TITLE
[Bug]: 大量批量导出漫画异常

### ISSUE THREAD

**Issue by ray4b** [wgh136/PicaComic#456]
### 描述/Description

开发者你好，首先非常感谢您在v3.0.5加入了批量导出漫画功能。我在使用此功能过程中遇到了个问题，并且可以稳定复现。具体问题为：如果一次性选择漫画数量过多，它在进行一半时会强行终止，并且导出一个损坏的压缩包文件。
如图所示，我选择了我收藏夹里50个占用空间最大的漫画进行导出，总大小理应约为30G左右，可实际导出到桌面的压缩包只有7.08G，且是损坏的，还有在软件下载目录里有一个相同大小的压缩包，同为损坏的。我查看了日志，它只有进程无法访问这一项错误，并无其他错误。我不太清楚github的规则，不知道能否发带有r18画面的录屏，所以我只提供了一张截图。如果可以发录屏且您需要的话我可以另外提供。希望能修复这个错误，感谢。

### Version

latest v3.0.5

### 使用的操作系统/Operating system

Windows

### 日志/logs

PathAccessException: Cannot delete file, path = 'C:\AAAPrograms\PicaComic\temp/comics.zip' (OS Error: 另一个程序正在使用此文件，进程无法访问。
, errno = 32)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File._delete.<anonymous closure> (dart:io/file_impl.dart:315)
#2      _rootRunUnary (dart:async/zone.dart:1407)
#3      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:838)
#4      Future._propagateToListeners (dart:async/future_impl.dart:867)
#5      Future._completeWithValue (dart:async/future_impl.dart:643)
#6      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:713)
#7      _rootRun (dart:async/zone.dart:1399)
#8      _CustomZone.run (dart:async/zone.dart:1301)
#9      _CustomZone.runGuarded (dart:async/zone.dart:1209)
#10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

### 截图或视频/Screenshot or video

![微信图片_20240401235421](https://github.com/wgh136/PicaComic/assets/42658567/4ce40d9f-8e07-4f79-a2b1-25be4c00882c)

**Comment by ray4b** [comment]
同样是选择了50个漫画的情况下，每次导出的压缩包大小都不一样，第一次2.19G就停止了，第二次是14.6G，第三次就是这7.08G，不过显然都是未完成的，并且文件是损坏的
