### ISSUE TITLE
e站白屏

### ISSUE THREAD

**Issue by ametoyuki098** [wgh136/PicaComic#66]
e站成功登录，但是无任何内容。

**Comment by wgh136** [comment]
看看日志, 有没有什么报错

**Comment by ametoyuki098** [comment]
我重新试了下，昨天可能是我节点问题并使用了“在webview中登录” 现在使用cookie登录可以正常使用了。 抱歉，以后我会多次尝试以确保自己的操作问题。

**Comment by wgh136** [comment]
看了下我这边收到的错误日志有几份是eh网络请求时的cookie错误, 比如说下面这两个:
```
1.6.16
FormatException: Invalid character in cookie value, code unit: '65281' (at character 12)
zqr21072004！
           ^

#0      _Cookie._validateValue (dart:_http/http_headers.dart:1150)
#1      new _Cookie (dart:_http/http_headers.dart:955)
#2      new Cookie (dart:_http:790)
#3      EhNetwork.request (package:pica_comic/network/eh_network/eh_main_network.dart:83)
#4      EhNetwork.getGalleries (package:pica_comic/network/eh_network/eh_main_network.dart:283)
#5      EhHomePageLogic.getGallery (package:pica_comic/views/eh_views/eh_home_page.dart:16)
```

```
1.6.16
FormatException: Invalid character in cookie value, code unit: '32' (at character 4)
cyy 19960601
   ^

#0      _Cookie._validateValue (dart:_http/http_headers.dart:1150)
#1      new _Cookie (dart:_http/http_headers.dart:955)
#2      new Cookie (dart:_http:790)
#3      EhNetwork.request (package:pica_comic/network/eh_network/eh_main_network.dart:83)
#4      EhNetwork.getGalleries (package:pica_comic/network/eh_network/eh_main_network.dart:283)
#5      _MainPageState.initState (package:pica_comic/views/main_page.dart:62)
```
cookie中出现了不应该出现的字符(感叹号和空格), 暂不清楚为什么拿到的cookie会是这样的, 等有时间再尝试解决
总之现在如果webview登录有问题, 就先使用cookie登录吧

**Comment by wgh136** [comment]
仍然不清楚为什么获取到的cookie是这样的, 加上了一个Cookie验证, 避免使用不正确的cookie进行网络请求
